# Generated by Django 5.2 on 2025-05-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_events',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.event'),
        ),
    ]
