name: Continuous Delivery

# Este workflow se activa cuando se publica una nueva versión en GitHub.
on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login en Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Obtener timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Buildear y Pushear
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ing-soft:latest,${{ secrets.DOCKERHUB_USERNAME }}/ing-soft:${{ env.timestamp }}
